// Resolves item/monster icon URLs from the Idle Clans community wiki
// (idleclans.wiki, a MediaWiki site) and writes them to src/data/icons.ts.
// Run with: node scripts/generate-icons.mjs
//
// The official game API (Configuration/game-data) has NO icon field at all —
// items and monsters are pure stat data, nothing image-related. The wiki is
// the only available source. Its MediaWiki API resolves a File: title to
// its real, hash-prefixed image URL (e.g. /w/images/5/59/Spruce_log.png) —
// the hash directory is unpredictable, so this must be looked up per name,
// not guessed/constructed. Filenames follow the wiki's own convention:
// sentence-case of the raw snake_case name with underscores replaced by
// spaces (e.g. "outstanding_scimitar" -> "Outstanding scimitar.png") — NOT
// our Title-Case `displayName`, which does not resolve (verified manually
// before writing this script).
//
// Icons are hotlinked from the wiki at runtime (src/data/icons.ts stores
// wiki URLs, not local copies) — per-project decision, 2026-06-23.

const res = await fetch('https://query.idleclans.com/api/Configuration/game-data')
const raw = await res.text()
const cleaned = raw
  .replace(/ObjectId\("[a-f0-9]+"\)/g, 'null')
  .replace(/ISODate\("[^"]*"\)/g, 'null')
const data = JSON.parse(cleaned)

const items = data.Items.Items.map((item) => ({ id: item.ItemId, name: item.Name }))
const monsters = data.Tasks.Combat.flatMap((group) => group.Items).map((m) => ({
  id: m.TaskId,
  name: m.Name,
}))

// The 21 raw skill keys the live API actually returns (verified against
// GET /api/Player/profile/{name}'s skillExperiences, 2026-06-23) — not the
// 22-skill union CLAUDE.md's data model lists (no "rigour" key ever shows up
// from the real API).
const SKILL_NAMES = [
  'attack', 'strength', 'defence', 'archery', 'magic', 'health', 'crafting',
  'woodcutting', 'carpentry', 'fishing', 'cooking', 'mining', 'smithing',
  'foraging', 'farming', 'agility', 'plundering', 'enchanting', 'brewing',
  'exterminating', 'invocation',
]
const skills = SKILL_NAMES.map((name) => ({ id: name, name }))

// "Attack" has no dedicated wiki file (File:Attack.png doesn't exist — the
// /w/Attack page itself redirects to /w/Combat, confirmed via the wiki's own
// API redirects=1 lookup, not guessed). Combat.png is the closest real
// match the wiki offers; every other skill resolves under its own name.
const WIKI_TITLE_OVERRIDES = { attack: 'Combat' }

function toWikiFileTitle(snakeCaseName) {
  if (WIKI_TITLE_OVERRIDES[snakeCaseName]) return `File:${WIKI_TITLE_OVERRIDES[snakeCaseName]}.png`
  // Enchanted items have no visual difference from their base version — the
  // wiki uses the same image file for both, without an "_enchanted" variant.
  const baseName = snakeCaseName.replace(/_enchanted$/, '')
  const sentenceCase = baseName
    .split('_')
    .map((word, i) => (i === 0 ? word.charAt(0).toUpperCase() + word.slice(1) : word))
    .join(' ')
  return `File:${sentenceCase}.png`
}

async function resolveBatch(entries) {
  const titleToEntry = new Map(entries.map((e) => [toWikiFileTitle(e.name), e]))
  const titles = [...titleToEntry.keys()].join('|')
  const url = `https://idleclans.wiki/w/api.php?action=query&titles=${encodeURIComponent(titles)}&prop=imageinfo&iiprop=url&format=json`
  const res = await fetch(url, { headers: { 'User-Agent': 'idle-clanner icon resolver (one-off script)' } })
  const json = await res.json()
  const pages = Object.values(json.query?.pages ?? {})

  // The API "normalizes" titles (e.g. underscore -> space) and reports the
  // mapping under query.normalized — without consulting it we can't match
  // a returned page back to the title we asked for.
  const normalizedFrom = new Map(
    (json.query?.normalized ?? []).map((n) => [n.to, n.from]),
  )

  const resolved = new Map()
  for (const page of pages) {
    if (page.missing !== undefined) continue
    const askedTitle = normalizedFrom.get(page.title) ?? page.title
    const entry = titleToEntry.get(askedTitle)
    const imageUrl = page.imageinfo?.[0]?.url
    if (entry && imageUrl) resolved.set(entry.id, imageUrl)
  }
  return resolved
}

async function resolveAll(entries, label) {
  const BATCH_SIZE = 50
  const result = new Map()
  for (let i = 0; i < entries.length; i += BATCH_SIZE) {
    const batch = entries.slice(i, i + BATCH_SIZE)
    const resolved = await resolveBatch(batch)
    for (const [id, url] of resolved) result.set(id, url)
    console.log(`${label}: resolved ${result.size}/${i + batch.length} so far`)
  }
  return result
}

const itemIcons = await resolveAll(items, 'items')
const monsterIcons = await resolveAll(monsters, 'monsters')
const skillIcons = await resolveAll(skills, 'skills')

const header = `// Generated by scripts/generate-icons.mjs. Do not hand-edit — rerun the
// script to regenerate.
//
// Icon URLs are resolved from the Idle Clans community wiki
// (idleclans.wiki), the only available icon source — the official game API
// has no icon field. Hotlinked, not downloaded locally. A missing entry
// means the wiki has no image file under the expected name for that
// item/monster (not necessarily that the item has no icon in-game).

export const ITEM_ICON_URLS: Map<number, string> = new Map(${JSON.stringify([...itemIcons], null, 2)})

export const MONSTER_ICON_URLS: Map<number, string> = new Map(${JSON.stringify([...monsterIcons], null, 2)})

// Keyed by the raw skill name as the API returns it (e.g. "woodcutting"),
// same key space as PlayerProfile.skills. "attack" resolves to the wiki's
// Combat.png — see WIKI_TITLE_OVERRIDES above for why.
export const SKILL_ICON_URLS: Map<string, string> = new Map(${JSON.stringify([...skillIcons], null, 2)})
`

const fs = await import('node:fs/promises')
await fs.writeFile(new URL('../src/data/icons.ts', import.meta.url), header)

console.log(
  `Wrote ${itemIcons.size}/${items.length} item icons, ${monsterIcons.size}/${monsters.length} monster icons, and ${skillIcons.size}/${skills.length} skill icons to src/data/icons.ts`,
)
