// Regenerates src/data/items.ts from the live Idle Clans game-data endpoint.
// Run with: node scripts/generate-items.mjs
//
// The endpoint returns MongoDB extended-JSON (ObjectId(...) wrappers), so we
// strip those before parsing. Source of truth: the game's own item
// definitions, not a guess or a wiki transcription.

const res = await fetch('https://query.idleclans.com/api/Configuration/game-data')
const raw = await res.text()
const cleaned = raw
  .replace(/ObjectId\("[a-f0-9]+"\)/g, 'null')
  .replace(/ISODate\("[^"]*"\)/g, 'null')
const data = JSON.parse(cleaned)

const items = data.Items.Items

function toDisplayName(snakeCase) {
  return snakeCase
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

const entries = items.map((item) => ({
  id: item.ItemId,
  name: item.Name,
  displayName: toDisplayName(item.Name),
  baseValue: item.BaseValue, // local/NPC shop sell price — what ironman accounts actually receive
  tradeable: !item.CanNotBeTraded && !item.Discontinued,
  shopSellable: !item.CanNotBeSoldToGameShop,
  // Raw numeric codes from the API. Not yet decoded to named enums (would be
  // guessing) — decode only once a feature actually needs them (Phase 3/4).
  category: item.Category,
  equipmentSlot: item.EquipmentSlot,
}))

entries.sort((a, b) => a.id - b.id)

const header = `// Generated by scripts/generate-items.mjs from GET /api/Configuration/game-data.
// Source of truth: the game's own item definitions. Do not hand-edit — rerun
// the script to regenerate after a game update.

export interface ItemDefinition {
  id: number
  name: string          // raw snake_case name from the API
  displayName: string   // formatted for UI display
  baseValue: number    // local/NPC shop sell price
  tradeable: boolean
  shopSellable: boolean // false for the ~25 items the local shop won't buy at all
  category: number       // raw API enum code, not yet decoded
  equipmentSlot: number  // raw API enum code, not yet decoded
}

export const ITEMS: ItemDefinition[] = `

const footer = `

export const ITEMS_BY_ID: Map<number, ItemDefinition> = new Map(ITEMS.map((item) => [item.id, item]))
`

const body = JSON.stringify(entries, null, 2)

const fs = await import('node:fs/promises')
await fs.writeFile(new URL('../src/data/items.ts', import.meta.url), header + body + footer)

console.log(`Wrote ${entries.length} items to src/data/items.ts`)
