// Generated by scripts/generate-activities.mjs from GET /api/Configuration/game-data
// (Tasks.<skill>). Do not hand-edit — rerun the script to regenerate.

export interface ActivityItemAmount {
  itemId: number
  quantity: number
}

export interface ActivityDefinition {
  id: string // `${skillKey}_${taskId}` — taskId alone is only unique within a skill
  taskId: number
  name: string
  skillKey: string // raw API skill grouping, e.g. "Mining", "Smithing"
  levelRequired: number
  baseActionsPerHour: number // derived: 3,600,000 / BaseTime(ms)
  xpPerAction: number
  outputItems: ActivityItemAmount[]
  inputItems: ActivityItemAmount[]
}

export const ACTIVITIES: ActivityDefinition[] = [
  {
    "id": "Agility_0",
    "taskId": 0,
    "name": "jogging_course",
    "skillKey": "Agility",
    "levelRequired": 1,
    "baseActionsPerHour": 600,
    "xpPerAction": 30,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Agility_1",
    "taskId": 1,
    "name": "swimming",
    "skillKey": "Agility",
    "levelRequired": 15,
    "baseActionsPerHour": 480,
    "xpPerAction": 40,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Agility_2",
    "taskId": 2,
    "name": "monkey_bars",
    "skillKey": "Agility",
    "levelRequired": 30,
    "baseActionsPerHour": 424,
    "xpPerAction": 55,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Agility_3",
    "taskId": 3,
    "name": "strength_training",
    "skillKey": "Agility",
    "levelRequired": 40,
    "baseActionsPerHour": 379,
    "xpPerAction": 70,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Agility_4",
    "taskId": 4,
    "name": "basic_obstacle_course",
    "skillKey": "Agility",
    "levelRequired": 55,
    "baseActionsPerHour": 327,
    "xpPerAction": 90,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Agility_5",
    "taskId": 5,
    "name": "combat_training",
    "skillKey": "Agility",
    "levelRequired": 70,
    "baseActionsPerHour": 288,
    "xpPerAction": 105,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Agility_6",
    "taskId": 6,
    "name": "military_obstacle_course",
    "skillKey": "Agility",
    "levelRequired": 80,
    "baseActionsPerHour": 277,
    "xpPerAction": 120,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Agility_7",
    "taskId": 7,
    "name": "rock_climbing",
    "skillKey": "Agility",
    "levelRequired": 90,
    "baseActionsPerHour": 240,
    "xpPerAction": 160,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Agility_8",
    "taskId": 8,
    "name": "the_summit",
    "skillKey": "Agility",
    "levelRequired": 105,
    "baseActionsPerHour": 14,
    "xpPerAction": 2520,
    "outputItems": [
      {
        "itemId": 915,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Brewing_0",
    "taskId": 0,
    "name": "potion_of_swiftness",
    "skillKey": "Brewing",
    "levelRequired": 1,
    "baseActionsPerHour": 65,
    "xpPerAction": 750,
    "outputItems": [
      {
        "itemId": 408,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 134,
        "quantity": 10
      },
      {
        "itemId": 118,
        "quantity": 5
      },
      {
        "itemId": 1,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Brewing_1",
    "taskId": 1,
    "name": "potion_of_negotiation",
    "skillKey": "Brewing",
    "levelRequired": 15,
    "baseActionsPerHour": 55,
    "xpPerAction": 1045,
    "outputItems": [
      {
        "itemId": 409,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 134,
        "quantity": 10
      },
      {
        "itemId": 273,
        "quantity": 15
      },
      {
        "itemId": 6,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Brewing_2",
    "taskId": 2,
    "name": "potion_of_resurrection",
    "skillKey": "Brewing",
    "levelRequired": 30,
    "baseActionsPerHour": 50,
    "xpPerAction": 1215,
    "outputItems": [
      {
        "itemId": 410,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 135,
        "quantity": 15
      },
      {
        "itemId": 274,
        "quantity": 10
      },
      {
        "itemId": 2,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Brewing_3",
    "taskId": 3,
    "name": "potion_of_forgery",
    "skillKey": "Brewing",
    "levelRequired": 45,
    "baseActionsPerHour": 42,
    "xpPerAction": 1515,
    "outputItems": [
      {
        "itemId": 411,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 136,
        "quantity": 10
      },
      {
        "itemId": 274,
        "quantity": 15
      },
      {
        "itemId": 9,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Brewing_4",
    "taskId": 4,
    "name": "potion_of_great_sight",
    "skillKey": "Brewing",
    "levelRequired": 55,
    "baseActionsPerHour": 37,
    "xpPerAction": 1950,
    "outputItems": [
      {
        "itemId": 412,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 137,
        "quantity": 10
      },
      {
        "itemId": 273,
        "quantity": 15
      },
      {
        "itemId": 8,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Brewing_5",
    "taskId": 5,
    "name": "potion_of_trickery",
    "skillKey": "Brewing",
    "levelRequired": 65,
    "baseActionsPerHour": 31,
    "xpPerAction": 2445,
    "outputItems": [
      {
        "itemId": 413,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 401,
        "quantity": 10
      },
      {
        "itemId": 125,
        "quantity": 15
      },
      {
        "itemId": 10,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Brewing_6",
    "taskId": 6,
    "name": "potion_of_dark_magic",
    "skillKey": "Brewing",
    "levelRequired": 75,
    "baseActionsPerHour": 27,
    "xpPerAction": 2950,
    "outputItems": [
      {
        "itemId": 414,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 403,
        "quantity": 10
      },
      {
        "itemId": 275,
        "quantity": 15
      },
      {
        "itemId": 406,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Brewing_7",
    "taskId": 7,
    "name": "potion_of_pure_power",
    "skillKey": "Brewing",
    "levelRequired": 85,
    "baseActionsPerHour": 23,
    "xpPerAction": 3750,
    "outputItems": [
      {
        "itemId": 415,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 403,
        "quantity": 15
      },
      {
        "itemId": 399,
        "quantity": 20
      },
      {
        "itemId": 407,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Brewing_8",
    "taskId": 8,
    "name": "potion_of_ancient_knowledge",
    "skillKey": "Brewing",
    "levelRequired": 93,
    "baseActionsPerHour": 20,
    "xpPerAction": 5025,
    "outputItems": [
      {
        "itemId": 416,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 405,
        "quantity": 20
      },
      {
        "itemId": 399,
        "quantity": 50
      },
      {
        "itemId": 407,
        "quantity": 10
      }
    ]
  },
  {
    "id": "Brewing_21",
    "taskId": 21,
    "name": "dragonfire_potion",
    "skillKey": "Brewing",
    "levelRequired": 105,
    "baseActionsPerHour": 40,
    "xpPerAction": 2950,
    "outputItems": [
      {
        "itemId": 917,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 916,
        "quantity": 10
      },
      {
        "itemId": 914,
        "quantity": 30
      },
      {
        "itemId": 913,
        "quantity": 5
      },
      {
        "itemId": 818,
        "quantity": 100
      }
    ]
  },
  {
    "id": "Brewing_22",
    "taskId": 22,
    "name": "potion_of_ascension",
    "skillKey": "Brewing",
    "levelRequired": 115,
    "baseActionsPerHour": 32,
    "xpPerAction": 3982,
    "outputItems": [
      {
        "itemId": 964,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 963,
        "quantity": 10
      },
      {
        "itemId": 960,
        "quantity": 30
      },
      {
        "itemId": 961,
        "quantity": 30
      },
      {
        "itemId": 962,
        "quantity": 50
      }
    ]
  },
  {
    "id": "Carpentry_0",
    "taskId": 0,
    "name": "spruce_plank",
    "skillKey": "Carpentry",
    "levelRequired": 1,
    "baseActionsPerHour": 400,
    "xpPerAction": 40,
    "outputItems": [
      {
        "itemId": 20,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 0,
        "quantity": 1
      },
      {
        "itemId": 19,
        "quantity": 50
      }
    ]
  },
  {
    "id": "Carpentry_1",
    "taskId": 1,
    "name": "pine_plank",
    "skillKey": "Carpentry",
    "levelRequired": 10,
    "baseActionsPerHour": 400,
    "xpPerAction": 45,
    "outputItems": [
      {
        "itemId": 21,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 1,
        "quantity": 1
      },
      {
        "itemId": 19,
        "quantity": 60
      }
    ]
  },
  {
    "id": "Carpentry_2",
    "taskId": 2,
    "name": "oak_plank",
    "skillKey": "Carpentry",
    "levelRequired": 20,
    "baseActionsPerHour": 400,
    "xpPerAction": 50,
    "outputItems": [
      {
        "itemId": 23,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 6,
        "quantity": 1
      },
      {
        "itemId": 19,
        "quantity": 70
      }
    ]
  },
  {
    "id": "Carpentry_3",
    "taskId": 3,
    "name": "maple_plank",
    "skillKey": "Carpentry",
    "levelRequired": 30,
    "baseActionsPerHour": 400,
    "xpPerAction": 55,
    "outputItems": [
      {
        "itemId": 24,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 7,
        "quantity": 1
      },
      {
        "itemId": 19,
        "quantity": 80
      }
    ]
  },
  {
    "id": "Carpentry_4",
    "taskId": 4,
    "name": "teak_plank",
    "skillKey": "Carpentry",
    "levelRequired": 40,
    "baseActionsPerHour": 400,
    "xpPerAction": 60,
    "outputItems": [
      {
        "itemId": 25,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 8,
        "quantity": 1
      },
      {
        "itemId": 19,
        "quantity": 90
      }
    ]
  },
  {
    "id": "Carpentry_5",
    "taskId": 5,
    "name": "chestnut_plank",
    "skillKey": "Carpentry",
    "levelRequired": 50,
    "baseActionsPerHour": 400,
    "xpPerAction": 70,
    "outputItems": [
      {
        "itemId": 22,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 2,
        "quantity": 1
      },
      {
        "itemId": 19,
        "quantity": 100
      }
    ]
  },
  {
    "id": "Carpentry_6",
    "taskId": 6,
    "name": "mahogany_plank",
    "skillKey": "Carpentry",
    "levelRequired": 60,
    "baseActionsPerHour": 400,
    "xpPerAction": 80,
    "outputItems": [
      {
        "itemId": 26,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 9,
        "quantity": 1
      },
      {
        "itemId": 19,
        "quantity": 110
      }
    ]
  },
  {
    "id": "Carpentry_7",
    "taskId": 7,
    "name": "yew_plank",
    "skillKey": "Carpentry",
    "levelRequired": 70,
    "baseActionsPerHour": 400,
    "xpPerAction": 95,
    "outputItems": [
      {
        "itemId": 27,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 10,
        "quantity": 1
      },
      {
        "itemId": 19,
        "quantity": 125
      }
    ]
  },
  {
    "id": "Carpentry_8",
    "taskId": 8,
    "name": "redwood_plank",
    "skillKey": "Carpentry",
    "levelRequired": 80,
    "baseActionsPerHour": 300,
    "xpPerAction": 140,
    "outputItems": [
      {
        "itemId": 586,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 406,
        "quantity": 1
      },
      {
        "itemId": 19,
        "quantity": 150
      }
    ]
  },
  {
    "id": "Carpentry_9",
    "taskId": 9,
    "name": "magical_plank",
    "skillKey": "Carpentry",
    "levelRequired": 90,
    "baseActionsPerHour": 240,
    "xpPerAction": 200,
    "outputItems": [
      {
        "itemId": 587,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 407,
        "quantity": 1
      },
      {
        "itemId": 19,
        "quantity": 175
      }
    ]
  },
  {
    "id": "Carpentry_10",
    "taskId": 10,
    "name": "ignis_heartwood",
    "skillKey": "Carpentry",
    "levelRequired": 105,
    "baseActionsPerHour": 27,
    "xpPerAction": 2000,
    "outputItems": [
      {
        "itemId": 913,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 912,
        "quantity": 3
      },
      {
        "itemId": 19,
        "quantity": 175
      }
    ]
  },
  {
    "id": "Cooking_0",
    "taskId": 0,
    "name": "cooked_piranha",
    "skillKey": "Cooking",
    "levelRequired": 1,
    "baseActionsPerHour": 1200,
    "xpPerAction": 10,
    "outputItems": [
      {
        "itemId": 160,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 159,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_1",
    "taskId": 1,
    "name": "cooked_perch",
    "skillKey": "Cooking",
    "levelRequired": 10,
    "baseActionsPerHour": 1029,
    "xpPerAction": 16,
    "outputItems": [
      {
        "itemId": 102,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 4,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_2",
    "taskId": 2,
    "name": "cooked_mackerel",
    "skillKey": "Cooking",
    "levelRequired": 15,
    "baseActionsPerHour": 900,
    "xpPerAction": 20,
    "outputItems": [
      {
        "itemId": 100,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 12,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_3",
    "taskId": 3,
    "name": "cooked_cod",
    "skillKey": "Cooking",
    "levelRequired": 20,
    "baseActionsPerHour": 800,
    "xpPerAction": 26,
    "outputItems": [
      {
        "itemId": 164,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 163,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_4",
    "taskId": 4,
    "name": "cooked_trout",
    "skillKey": "Cooking",
    "levelRequired": 25,
    "baseActionsPerHour": 720,
    "xpPerAction": 33,
    "outputItems": [
      {
        "itemId": 104,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 13,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_5",
    "taskId": 5,
    "name": "cooked_salmon",
    "skillKey": "Cooking",
    "levelRequired": 30,
    "baseActionsPerHour": 600,
    "xpPerAction": 40,
    "outputItems": [
      {
        "itemId": 105,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 14,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_6",
    "taskId": 6,
    "name": "cooked_carp",
    "skillKey": "Cooking",
    "levelRequired": 40,
    "baseActionsPerHour": 480,
    "xpPerAction": 56,
    "outputItems": [
      {
        "itemId": 106,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 15,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_7",
    "taskId": 7,
    "name": "cooked_zander",
    "skillKey": "Cooking",
    "levelRequired": 50,
    "baseActionsPerHour": 360,
    "xpPerAction": 80,
    "outputItems": [
      {
        "itemId": 158,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 157,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_8",
    "taskId": 8,
    "name": "cooked_pufferfish",
    "skillKey": "Cooking",
    "levelRequired": 60,
    "baseActionsPerHour": 288,
    "xpPerAction": 105,
    "outputItems": [
      {
        "itemId": 162,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 161,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_9",
    "taskId": 9,
    "name": "cooked_anglerfish",
    "skillKey": "Cooking",
    "levelRequired": 70,
    "baseActionsPerHour": 206,
    "xpPerAction": 155,
    "outputItems": [
      {
        "itemId": 156,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 155,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_10",
    "taskId": 10,
    "name": "cooked_tuna",
    "skillKey": "Cooking",
    "levelRequired": 85,
    "baseActionsPerHour": 137,
    "xpPerAction": 255,
    "outputItems": [
      {
        "itemId": 562,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 561,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_11",
    "taskId": 11,
    "name": "cooked_bloodmoon_eel",
    "skillKey": "Cooking",
    "levelRequired": 95,
    "baseActionsPerHour": 55,
    "xpPerAction": 892,
    "outputItems": [
      {
        "itemId": 888,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 887,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_12",
    "taskId": 12,
    "name": "cooked_meat",
    "skillKey": "Cooking",
    "levelRequired": 10,
    "baseActionsPerHour": 1440,
    "xpPerAction": 30,
    "outputItems": [
      {
        "itemId": 114,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 110,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_13",
    "taskId": 13,
    "name": "cooked_giant_meat",
    "skillKey": "Cooking",
    "levelRequired": 30,
    "baseActionsPerHour": 900,
    "xpPerAction": 60,
    "outputItems": [
      {
        "itemId": 115,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 111,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_14",
    "taskId": 14,
    "name": "cooked_quality_meat",
    "skillKey": "Cooking",
    "levelRequired": 60,
    "baseActionsPerHour": 600,
    "xpPerAction": 120,
    "outputItems": [
      {
        "itemId": 116,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 112,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_15",
    "taskId": 15,
    "name": "cooked_superior_meat",
    "skillKey": "Cooking",
    "levelRequired": 90,
    "baseActionsPerHour": 360,
    "xpPerAction": 250,
    "outputItems": [
      {
        "itemId": 117,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 113,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_16",
    "taskId": 16,
    "name": "cooked_apex_meat",
    "skillKey": "Cooking",
    "levelRequired": 100,
    "baseActionsPerHour": 300,
    "xpPerAction": 350,
    "outputItems": [
      {
        "itemId": 906,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 905,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_17",
    "taskId": 17,
    "name": "potato_soup",
    "skillKey": "Cooking",
    "levelRequired": 15,
    "baseActionsPerHour": 1440,
    "xpPerAction": 40,
    "outputItems": [
      {
        "itemId": 140,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 132,
        "quantity": 3
      }
    ]
  },
  {
    "id": "Cooking_18",
    "taskId": 18,
    "name": "meat_burger",
    "skillKey": "Cooking",
    "levelRequired": 25,
    "baseActionsPerHour": 900,
    "xpPerAction": 75,
    "outputItems": [
      {
        "itemId": 141,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 114,
        "quantity": 2
      },
      {
        "itemId": 138,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_19",
    "taskId": 19,
    "name": "cod_soup",
    "skillKey": "Cooking",
    "levelRequired": 40,
    "baseActionsPerHour": 655,
    "xpPerAction": 150,
    "outputItems": [
      {
        "itemId": 143,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 164,
        "quantity": 2
      },
      {
        "itemId": 132,
        "quantity": 3
      },
      {
        "itemId": 138,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_20",
    "taskId": 20,
    "name": "blueberry_pie",
    "skillKey": "Cooking",
    "levelRequired": 50,
    "baseActionsPerHour": 600,
    "xpPerAction": 200,
    "outputItems": [
      {
        "itemId": 144,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 122,
        "quantity": 10
      },
      {
        "itemId": 273,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_21",
    "taskId": 21,
    "name": "salmon_salad",
    "skillKey": "Cooking",
    "levelRequired": 60,
    "baseActionsPerHour": 514,
    "xpPerAction": 250,
    "outputItems": [
      {
        "itemId": 145,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 105,
        "quantity": 2
      },
      {
        "itemId": 132,
        "quantity": 2
      },
      {
        "itemId": 138,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_22",
    "taskId": 22,
    "name": "porcini_soup",
    "skillKey": "Cooking",
    "levelRequired": 70,
    "baseActionsPerHour": 450,
    "xpPerAction": 400,
    "outputItems": [
      {
        "itemId": 146,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 125,
        "quantity": 5
      },
      {
        "itemId": 132,
        "quantity": 4
      },
      {
        "itemId": 138,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Cooking_23",
    "taskId": 23,
    "name": "stew",
    "skillKey": "Cooking",
    "levelRequired": 80,
    "baseActionsPerHour": 400,
    "xpPerAction": 550,
    "outputItems": [
      {
        "itemId": 559,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 132,
        "quantity": 2
      },
      {
        "itemId": 133,
        "quantity": 4
      },
      {
        "itemId": 116,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_24",
    "taskId": 24,
    "name": "power_pizza",
    "skillKey": "Cooking",
    "levelRequired": 95,
    "baseActionsPerHour": 360,
    "xpPerAction": 750,
    "outputItems": [
      {
        "itemId": 148,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 158,
        "quantity": 3
      },
      {
        "itemId": 162,
        "quantity": 1
      },
      {
        "itemId": 116,
        "quantity": 2
      },
      {
        "itemId": 138,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Cooking_25",
    "taskId": 25,
    "name": "cooked_sea_serpent",
    "skillKey": "Cooking",
    "levelRequired": 105,
    "baseActionsPerHour": 91,
    "xpPerAction": 446,
    "outputItems": [
      {
        "itemId": 957,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 956,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_7",
    "taskId": 7,
    "name": "leather_trousers",
    "skillKey": "Crafting",
    "levelRequired": 1,
    "baseActionsPerHour": 480,
    "xpPerAction": 30,
    "outputItems": [
      {
        "itemId": 258,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 245,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Crafting_8",
    "taskId": 8,
    "name": "leather_coat",
    "skillKey": "Crafting",
    "levelRequired": 1,
    "baseActionsPerHour": 480,
    "xpPerAction": 35,
    "outputItems": [
      {
        "itemId": 259,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 245,
        "quantity": 3
      }
    ]
  },
  {
    "id": "Crafting_9",
    "taskId": 9,
    "name": "orange_leather_trousers",
    "skillKey": "Crafting",
    "levelRequired": 20,
    "baseActionsPerHour": 480,
    "xpPerAction": 55,
    "outputItems": [
      {
        "itemId": 250,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 246,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Crafting_10",
    "taskId": 10,
    "name": "orange_leather_coat",
    "skillKey": "Crafting",
    "levelRequired": 20,
    "baseActionsPerHour": 480,
    "xpPerAction": 65,
    "outputItems": [
      {
        "itemId": 251,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 246,
        "quantity": 3
      }
    ]
  },
  {
    "id": "Crafting_11",
    "taskId": 11,
    "name": "green_leather_trousers",
    "skillKey": "Crafting",
    "levelRequired": 40,
    "baseActionsPerHour": 480,
    "xpPerAction": 85,
    "outputItems": [
      {
        "itemId": 252,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 247,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Crafting_12",
    "taskId": 12,
    "name": "green_leather_coat",
    "skillKey": "Crafting",
    "levelRequired": 40,
    "baseActionsPerHour": 480,
    "xpPerAction": 100,
    "outputItems": [
      {
        "itemId": 253,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 247,
        "quantity": 3
      }
    ]
  },
  {
    "id": "Crafting_13",
    "taskId": 13,
    "name": "red_leather_trousers",
    "skillKey": "Crafting",
    "levelRequired": 60,
    "baseActionsPerHour": 480,
    "xpPerAction": 110,
    "outputItems": [
      {
        "itemId": 254,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 248,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Crafting_14",
    "taskId": 14,
    "name": "red_leather_coat",
    "skillKey": "Crafting",
    "levelRequired": 60,
    "baseActionsPerHour": 480,
    "xpPerAction": 125,
    "outputItems": [
      {
        "itemId": 255,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 248,
        "quantity": 3
      }
    ]
  },
  {
    "id": "Crafting_15",
    "taskId": 15,
    "name": "black_leather_trousers",
    "skillKey": "Crafting",
    "levelRequired": 80,
    "baseActionsPerHour": 480,
    "xpPerAction": 150,
    "outputItems": [
      {
        "itemId": 256,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 249,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Crafting_16",
    "taskId": 16,
    "name": "black_leather_coat",
    "skillKey": "Crafting",
    "levelRequired": 80,
    "baseActionsPerHour": 480,
    "xpPerAction": 185,
    "outputItems": [
      {
        "itemId": 257,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 249,
        "quantity": 3
      }
    ]
  },
  {
    "id": "Crafting_17",
    "taskId": 17,
    "name": "basilisk_scale_trousers",
    "skillKey": "Crafting",
    "levelRequired": 85,
    "baseActionsPerHour": 480,
    "xpPerAction": 500,
    "outputItems": [
      {
        "itemId": 833,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 832,
        "quantity": 2
      },
      {
        "itemId": 256,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_18",
    "taskId": 18,
    "name": "basilisk_scale_coat",
    "skillKey": "Crafting",
    "levelRequired": 85,
    "baseActionsPerHour": 480,
    "xpPerAction": 500,
    "outputItems": [
      {
        "itemId": 834,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 832,
        "quantity": 3
      },
      {
        "itemId": 257,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_19",
    "taskId": 19,
    "name": "astronomical_leather_trousers",
    "skillKey": "Crafting",
    "levelRequired": 95,
    "baseActionsPerHour": 240,
    "xpPerAction": 1000,
    "outputItems": [
      {
        "itemId": 584,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 569,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Crafting_20",
    "taskId": 20,
    "name": "astronomical_leather_coat",
    "skillKey": "Crafting",
    "levelRequired": 95,
    "baseActionsPerHour": 240,
    "xpPerAction": 1000,
    "outputItems": [
      {
        "itemId": 583,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 569,
        "quantity": 6
      }
    ]
  },
  {
    "id": "Crafting_21",
    "taskId": 21,
    "name": "bronze_arrow",
    "skillKey": "Crafting",
    "levelRequired": 1,
    "baseActionsPerHour": 600,
    "xpPerAction": 20,
    "outputItems": [
      {
        "itemId": 260,
        "quantity": 10
      }
    ],
    "inputItems": [
      {
        "itemId": 34,
        "quantity": 1
      },
      {
        "itemId": 0,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_22",
    "taskId": 22,
    "name": "iron_arrow",
    "skillKey": "Crafting",
    "levelRequired": 10,
    "baseActionsPerHour": 600,
    "xpPerAction": 25,
    "outputItems": [
      {
        "itemId": 261,
        "quantity": 10
      }
    ],
    "inputItems": [
      {
        "itemId": 35,
        "quantity": 1
      },
      {
        "itemId": 1,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_23",
    "taskId": 23,
    "name": "steel_arrow",
    "skillKey": "Crafting",
    "levelRequired": 20,
    "baseActionsPerHour": 600,
    "xpPerAction": 30,
    "outputItems": [
      {
        "itemId": 262,
        "quantity": 10
      }
    ],
    "inputItems": [
      {
        "itemId": 36,
        "quantity": 1
      },
      {
        "itemId": 6,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_24",
    "taskId": 24,
    "name": "platinum_arrow",
    "skillKey": "Crafting",
    "levelRequired": 40,
    "baseActionsPerHour": 600,
    "xpPerAction": 35,
    "outputItems": [
      {
        "itemId": 263,
        "quantity": 10
      }
    ],
    "inputItems": [
      {
        "itemId": 43,
        "quantity": 1
      },
      {
        "itemId": 7,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_25",
    "taskId": 25,
    "name": "meteorite_arrow",
    "skillKey": "Crafting",
    "levelRequired": 60,
    "baseActionsPerHour": 600,
    "xpPerAction": 40,
    "outputItems": [
      {
        "itemId": 264,
        "quantity": 10
      }
    ],
    "inputItems": [
      {
        "itemId": 45,
        "quantity": 1
      },
      {
        "itemId": 8,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_26",
    "taskId": 26,
    "name": "titanium_arrow",
    "skillKey": "Crafting",
    "levelRequired": 70,
    "baseActionsPerHour": 600,
    "xpPerAction": 50,
    "outputItems": [
      {
        "itemId": 265,
        "quantity": 10
      }
    ],
    "inputItems": [
      {
        "itemId": 46,
        "quantity": 1
      },
      {
        "itemId": 9,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_27",
    "taskId": 27,
    "name": "astronomical_arrow",
    "skillKey": "Crafting",
    "levelRequired": 80,
    "baseActionsPerHour": 600,
    "xpPerAction": 80,
    "outputItems": [
      {
        "itemId": 266,
        "quantity": 1000
      }
    ],
    "inputItems": [
      {
        "itemId": 48,
        "quantity": 1
      },
      {
        "itemId": 10,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_31",
    "taskId": 31,
    "name": "magical_robe",
    "skillKey": "Crafting",
    "levelRequired": 20,
    "baseActionsPerHour": 480,
    "xpPerAction": 55,
    "outputItems": [
      {
        "itemId": 276,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 273,
        "quantity": 15
      }
    ]
  },
  {
    "id": "Crafting_32",
    "taskId": 32,
    "name": "magical_trousers",
    "skillKey": "Crafting",
    "levelRequired": 20,
    "baseActionsPerHour": 480,
    "xpPerAction": 48,
    "outputItems": [
      {
        "itemId": 277,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 273,
        "quantity": 10
      }
    ]
  },
  {
    "id": "Crafting_33",
    "taskId": 33,
    "name": "enchanted_robe",
    "skillKey": "Crafting",
    "levelRequired": 40,
    "baseActionsPerHour": 480,
    "xpPerAction": 70,
    "outputItems": [
      {
        "itemId": 278,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 274,
        "quantity": 15
      }
    ]
  },
  {
    "id": "Crafting_34",
    "taskId": 34,
    "name": "enchanted_trousers",
    "skillKey": "Crafting",
    "levelRequired": 40,
    "baseActionsPerHour": 480,
    "xpPerAction": 65,
    "outputItems": [
      {
        "itemId": 279,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 274,
        "quantity": 10
      }
    ]
  },
  {
    "id": "Crafting_35",
    "taskId": 35,
    "name": "cursed_robe",
    "skillKey": "Crafting",
    "levelRequired": 70,
    "baseActionsPerHour": 480,
    "xpPerAction": 125,
    "outputItems": [
      {
        "itemId": 280,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 275,
        "quantity": 15
      }
    ]
  },
  {
    "id": "Crafting_36",
    "taskId": 36,
    "name": "cursed_trousers",
    "skillKey": "Crafting",
    "levelRequired": 70,
    "baseActionsPerHour": 480,
    "xpPerAction": 110,
    "outputItems": [
      {
        "itemId": 281,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 275,
        "quantity": 10
      }
    ]
  },
  {
    "id": "Crafting_37",
    "taskId": 37,
    "name": "astronomical_robe",
    "skillKey": "Crafting",
    "levelRequired": 95,
    "baseActionsPerHour": 240,
    "xpPerAction": 1000,
    "outputItems": [
      {
        "itemId": 581,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 568,
        "quantity": 6
      }
    ]
  },
  {
    "id": "Crafting_38",
    "taskId": 38,
    "name": "astronomical_trousers",
    "skillKey": "Crafting",
    "levelRequired": 95,
    "baseActionsPerHour": 240,
    "xpPerAction": 1000,
    "outputItems": [
      {
        "itemId": 582,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 568,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Crafting_40",
    "taskId": 40,
    "name": "obsidian_powder",
    "skillKey": "Crafting",
    "levelRequired": 105,
    "baseActionsPerHour": 120,
    "xpPerAction": 508,
    "outputItems": [
      {
        "itemId": 960,
        "quantity": 10
      }
    ],
    "inputItems": [
      {
        "itemId": 959,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_41",
    "taskId": 41,
    "name": "sea_serpent_scale",
    "skillKey": "Crafting",
    "levelRequired": 110,
    "baseActionsPerHour": 96,
    "xpPerAction": 652,
    "outputItems": [
      {
        "itemId": 961,
        "quantity": 10
      }
    ],
    "inputItems": [
      {
        "itemId": 956,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_42",
    "taskId": 42,
    "name": "otherworldly_leather_coat",
    "skillKey": "Crafting",
    "levelRequired": 115,
    "baseActionsPerHour": 240,
    "xpPerAction": 2500,
    "outputItems": [
      {
        "itemId": 995,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 985,
        "quantity": 6
      },
      {
        "itemId": 583,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_43",
    "taskId": 43,
    "name": "otherworldly_leather_trousers",
    "skillKey": "Crafting",
    "levelRequired": 110,
    "baseActionsPerHour": 240,
    "xpPerAction": 2500,
    "outputItems": [
      {
        "itemId": 994,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 985,
        "quantity": 4
      },
      {
        "itemId": 584,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Crafting_44",
    "taskId": 44,
    "name": "obsidian_arrow",
    "skillKey": "Crafting",
    "levelRequired": 95,
    "baseActionsPerHour": 600,
    "xpPerAction": 98,
    "outputItems": [
      {
        "itemId": 998,
        "quantity": 10
      }
    ],
    "inputItems": [
      {
        "itemId": 959,
        "quantity": 1
      },
      {
        "itemId": 407,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Farming_0",
    "taskId": 0,
    "name": "potato",
    "skillKey": "Farming",
    "levelRequired": 1,
    "baseActionsPerHour": 120,
    "xpPerAction": 75,
    "outputItems": [
      {
        "itemId": 132,
        "quantity": 5
      }
    ],
    "inputItems": [
      {
        "itemId": 126,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Farming_1",
    "taskId": 1,
    "name": "carrot",
    "skillKey": "Farming",
    "levelRequired": 10,
    "baseActionsPerHour": 90,
    "xpPerAction": 200,
    "outputItems": [
      {
        "itemId": 133,
        "quantity": 5
      }
    ],
    "inputItems": [
      {
        "itemId": 127,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Farming_2",
    "taskId": 2,
    "name": "tomato",
    "skillKey": "Farming",
    "levelRequired": 20,
    "baseActionsPerHour": 60,
    "xpPerAction": 300,
    "outputItems": [
      {
        "itemId": 134,
        "quantity": 5
      }
    ],
    "inputItems": [
      {
        "itemId": 128,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Farming_3",
    "taskId": 3,
    "name": "cabbage",
    "skillKey": "Farming",
    "levelRequired": 25,
    "baseActionsPerHour": 60,
    "xpPerAction": 325,
    "outputItems": [
      {
        "itemId": 135,
        "quantity": 5
      }
    ],
    "inputItems": [
      {
        "itemId": 129,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Farming_4",
    "taskId": 4,
    "name": "strawberry",
    "skillKey": "Farming",
    "levelRequired": 35,
    "baseActionsPerHour": 40,
    "xpPerAction": 500,
    "outputItems": [
      {
        "itemId": 136,
        "quantity": 5
      }
    ],
    "inputItems": [
      {
        "itemId": 130,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Farming_5",
    "taskId": 5,
    "name": "watermelon",
    "skillKey": "Farming",
    "levelRequired": 50,
    "baseActionsPerHour": 30,
    "xpPerAction": 850,
    "outputItems": [
      {
        "itemId": 137,
        "quantity": 5
      }
    ],
    "inputItems": [
      {
        "itemId": 131,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Farming_6",
    "taskId": 6,
    "name": "grapes",
    "skillKey": "Farming",
    "levelRequired": 65,
    "baseActionsPerHour": 24,
    "xpPerAction": 1100,
    "outputItems": [
      {
        "itemId": 401,
        "quantity": 5
      }
    ],
    "inputItems": [
      {
        "itemId": 400,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Farming_7",
    "taskId": 7,
    "name": "papaya",
    "skillKey": "Farming",
    "levelRequired": 80,
    "baseActionsPerHour": 22,
    "xpPerAction": 1250,
    "outputItems": [
      {
        "itemId": 403,
        "quantity": 5
      }
    ],
    "inputItems": [
      {
        "itemId": 402,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Farming_8",
    "taskId": 8,
    "name": "dragonfruit",
    "skillKey": "Farming",
    "levelRequired": 90,
    "baseActionsPerHour": 20,
    "xpPerAction": 1500,
    "outputItems": [
      {
        "itemId": 405,
        "quantity": 5
      }
    ],
    "inputItems": [
      {
        "itemId": 404,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Farming_21",
    "taskId": 21,
    "name": "sunfire_berry",
    "skillKey": "Farming",
    "levelRequired": 105,
    "baseActionsPerHour": 11,
    "xpPerAction": 2850,
    "outputItems": [
      {
        "itemId": 916,
        "quantity": 5
      }
    ],
    "inputItems": [
      {
        "itemId": 915,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Fishing_0",
    "taskId": 0,
    "name": "piranha",
    "skillKey": "Fishing",
    "levelRequired": 1,
    "baseActionsPerHour": 686,
    "xpPerAction": 11.25,
    "outputItems": [
      {
        "itemId": 159,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Fishing_1",
    "taskId": 1,
    "name": "perch",
    "skillKey": "Fishing",
    "levelRequired": 10,
    "baseActionsPerHour": 480,
    "xpPerAction": 18.75,
    "outputItems": [
      {
        "itemId": 4,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Fishing_2",
    "taskId": 2,
    "name": "mackerel",
    "skillKey": "Fishing",
    "levelRequired": 15,
    "baseActionsPerHour": 400,
    "xpPerAction": 23.25,
    "outputItems": [
      {
        "itemId": 12,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Fishing_3",
    "taskId": 3,
    "name": "cod",
    "skillKey": "Fishing",
    "levelRequired": 20,
    "baseActionsPerHour": 300,
    "xpPerAction": 35.25,
    "outputItems": [
      {
        "itemId": 163,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Fishing_4",
    "taskId": 4,
    "name": "trout",
    "skillKey": "Fishing",
    "levelRequired": 25,
    "baseActionsPerHour": 400,
    "xpPerAction": 29,
    "outputItems": [
      {
        "itemId": 13,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Fishing_5",
    "taskId": 5,
    "name": "salmon",
    "skillKey": "Fishing",
    "levelRequired": 30,
    "baseActionsPerHour": 267,
    "xpPerAction": 45,
    "outputItems": [
      {
        "itemId": 14,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Fishing_6",
    "taskId": 6,
    "name": "carp",
    "skillKey": "Fishing",
    "levelRequired": 40,
    "baseActionsPerHour": 379,
    "xpPerAction": 33,
    "outputItems": [
      {
        "itemId": 15,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Fishing_7",
    "taskId": 7,
    "name": "zander",
    "skillKey": "Fishing",
    "levelRequired": 50,
    "baseActionsPerHour": 240,
    "xpPerAction": 54,
    "outputItems": [
      {
        "itemId": 157,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Fishing_8",
    "taskId": 8,
    "name": "pufferfish",
    "skillKey": "Fishing",
    "levelRequired": 60,
    "baseActionsPerHour": 192,
    "xpPerAction": 69,
    "outputItems": [
      {
        "itemId": 161,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Fishing_9",
    "taskId": 9,
    "name": "anglerfish",
    "skillKey": "Fishing",
    "levelRequired": 80,
    "baseActionsPerHour": 120,
    "xpPerAction": 123,
    "outputItems": [
      {
        "itemId": 155,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Fishing_10",
    "taskId": 10,
    "name": "tuna",
    "skillKey": "Fishing",
    "levelRequired": 90,
    "baseActionsPerHour": 80,
    "xpPerAction": 205,
    "outputItems": [
      {
        "itemId": 561,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Fishing_11",
    "taskId": 11,
    "name": "bloodmoon_eel",
    "skillKey": "Fishing",
    "levelRequired": 100,
    "baseActionsPerHour": 40,
    "xpPerAction": 610,
    "outputItems": [
      {
        "itemId": 887,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 886,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Fishing_12",
    "taskId": 12,
    "name": "sea_serpent",
    "skillKey": "Fishing",
    "levelRequired": 110,
    "baseActionsPerHour": 20,
    "xpPerAction": 1065,
    "outputItems": [
      {
        "itemId": 956,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Foraging_0",
    "taskId": 0,
    "name": "nettle",
    "skillKey": "Foraging",
    "levelRequired": 1,
    "baseActionsPerHour": 600,
    "xpPerAction": 15,
    "outputItems": [
      {
        "itemId": 118,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Foraging_1",
    "taskId": 1,
    "name": "kiwi",
    "skillKey": "Foraging",
    "levelRequired": 10,
    "baseActionsPerHour": 514,
    "xpPerAction": 20,
    "outputItems": [
      {
        "itemId": 165,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Foraging_2",
    "taskId": 2,
    "name": "onion",
    "skillKey": "Foraging",
    "levelRequired": 20,
    "baseActionsPerHour": 480,
    "xpPerAction": 25,
    "outputItems": [
      {
        "itemId": 138,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Foraging_3",
    "taskId": 3,
    "name": "magical_flax",
    "skillKey": "Foraging",
    "levelRequired": 30,
    "baseActionsPerHour": 450,
    "xpPerAction": 30,
    "outputItems": [
      {
        "itemId": 273,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Foraging_4",
    "taskId": 4,
    "name": "blueberries",
    "skillKey": "Foraging",
    "levelRequired": 40,
    "baseActionsPerHour": 450,
    "xpPerAction": 36,
    "outputItems": [
      {
        "itemId": 122,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Foraging_5",
    "taskId": 5,
    "name": "enchanted_flax",
    "skillKey": "Foraging",
    "levelRequired": 55,
    "baseActionsPerHour": 424,
    "xpPerAction": 44,
    "outputItems": [
      {
        "itemId": 274,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Foraging_6",
    "taskId": 6,
    "name": "porcini",
    "skillKey": "Foraging",
    "levelRequired": 70,
    "baseActionsPerHour": 400,
    "xpPerAction": 60,
    "outputItems": [
      {
        "itemId": 125,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Foraging_7",
    "taskId": 7,
    "name": "cursed_flax",
    "skillKey": "Foraging",
    "levelRequired": 80,
    "baseActionsPerHour": 360,
    "xpPerAction": 80,
    "outputItems": [
      {
        "itemId": 275,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Foraging_8",
    "taskId": 8,
    "name": "seaweed",
    "skillKey": "Foraging",
    "levelRequired": 90,
    "baseActionsPerHour": 288,
    "xpPerAction": 110,
    "outputItems": [
      {
        "itemId": 399,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Foraging_21",
    "taskId": 21,
    "name": "smoldering_mushroom",
    "skillKey": "Foraging",
    "levelRequired": 105,
    "baseActionsPerHour": 165,
    "xpPerAction": 210,
    "outputItems": [
      {
        "itemId": 914,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Invocation_0",
    "taskId": 0,
    "name": "abandoned_dig_site",
    "skillKey": "Invocation",
    "levelRequired": 1,
    "baseActionsPerHour": 65,
    "xpPerAction": 65,
    "outputItems": [],
    "inputItems": [
      {
        "itemId": 19,
        "quantity": 296
      }
    ]
  },
  {
    "id": "Invocation_1",
    "taskId": 1,
    "name": "lost_temple",
    "skillKey": "Invocation",
    "levelRequired": 30,
    "baseActionsPerHour": 44,
    "xpPerAction": 130,
    "outputItems": [],
    "inputItems": [
      {
        "itemId": 19,
        "quantity": 660
      }
    ]
  },
  {
    "id": "Invocation_2",
    "taskId": 2,
    "name": "ruined_citadel",
    "skillKey": "Invocation",
    "levelRequired": 50,
    "baseActionsPerHour": 29,
    "xpPerAction": 273,
    "outputItems": [],
    "inputItems": [
      {
        "itemId": 19,
        "quantity": 1552
      }
    ]
  },
  {
    "id": "Invocation_3",
    "taskId": 3,
    "name": "royal_necropolis",
    "skillKey": "Invocation",
    "levelRequired": 70,
    "baseActionsPerHour": 19,
    "xpPerAction": 600,
    "outputItems": [],
    "inputItems": [
      {
        "itemId": 19,
        "quantity": 4222
      }
    ]
  },
  {
    "id": "Invocation_4",
    "taskId": 4,
    "name": "sanctuary_of_kings",
    "skillKey": "Invocation",
    "levelRequired": 90,
    "baseActionsPerHour": 13,
    "xpPerAction": 1381,
    "outputItems": [],
    "inputItems": [
      {
        "itemId": 19,
        "quantity": 14387
      }
    ]
  },
  {
    "id": "Invocation_5",
    "taskId": 5,
    "name": "first_ascension",
    "skillKey": "Invocation",
    "levelRequired": 110,
    "baseActionsPerHour": 9,
    "xpPerAction": 3315,
    "outputItems": [],
    "inputItems": [
      {
        "itemId": 19,
        "quantity": 60354
      }
    ]
  },
  {
    "id": "ItemCreation_0",
    "taskId": 0,
    "name": "primeval_fangblade",
    "skillKey": "ItemCreation",
    "levelRequired": 90,
    "baseActionsPerHour": 360,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 894,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 48,
        "quantity": 1
      },
      {
        "itemId": 895,
        "quantity": 1
      },
      {
        "itemId": 416,
        "quantity": 25
      }
    ]
  },
  {
    "id": "ItemCreation_1",
    "taskId": 1,
    "name": "divine_hide_buckler",
    "skillKey": "ItemCreation",
    "levelRequired": 100,
    "baseActionsPerHour": 144,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 903,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 565,
        "quantity": 1
      },
      {
        "itemId": 904,
        "quantity": 5
      }
    ]
  },
  {
    "id": "ItemCreation_2",
    "taskId": 2,
    "name": "nagas_blessed_crown",
    "skillKey": "ItemCreation",
    "levelRequired": 105,
    "baseActionsPerHour": 144,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 907,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 841,
        "quantity": 1
      },
      {
        "itemId": 908,
        "quantity": 1
      }
    ]
  },
  {
    "id": "ItemCreation_3",
    "taskId": 3,
    "name": "grimwark_shield",
    "skillKey": "ItemCreation",
    "levelRequired": 105,
    "baseActionsPerHour": 360,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 920,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 919,
        "quantity": 1
      },
      {
        "itemId": 563,
        "quantity": 1
      }
    ]
  },
  {
    "id": "ItemCreation_4",
    "taskId": 4,
    "name": "otherworldly_dragonscale_shield",
    "skillKey": "ItemCreation",
    "levelRequired": 112,
    "baseActionsPerHour": 144,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 918,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 921,
        "quantity": 1
      },
      {
        "itemId": 677,
        "quantity": 1
      }
    ]
  },
  {
    "id": "ItemCreation_5",
    "taskId": 5,
    "name": "otherworldly_dragon_slayer_crossbow",
    "skillKey": "ItemCreation",
    "levelRequired": 115,
    "baseActionsPerHour": 144,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 928,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 795,
        "quantity": 1
      },
      {
        "itemId": 566,
        "quantity": 1
      },
      {
        "itemId": 929,
        "quantity": 1
      }
    ]
  },
  {
    "id": "ItemCreation_6",
    "taskId": 6,
    "name": "citadel_helmet",
    "skillKey": "ItemCreation",
    "levelRequired": 70,
    "baseActionsPerHour": 144,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 974,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 971,
        "quantity": 1
      },
      {
        "itemId": 564,
        "quantity": 1
      }
    ]
  },
  {
    "id": "ItemCreation_7",
    "taskId": 7,
    "name": "citadel_platelegs",
    "skillKey": "ItemCreation",
    "levelRequired": 70,
    "baseActionsPerHour": 144,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 975,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 972,
        "quantity": 1
      },
      {
        "itemId": 812,
        "quantity": 1
      }
    ]
  },
  {
    "id": "ItemCreation_8",
    "taskId": 8,
    "name": "citadel_platebody",
    "skillKey": "ItemCreation",
    "levelRequired": 70,
    "baseActionsPerHour": 144,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 976,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 973,
        "quantity": 1
      },
      {
        "itemId": 673,
        "quantity": 1
      }
    ]
  },
  {
    "id": "ItemCreation_9",
    "taskId": 9,
    "name": "pharaohs_boots",
    "skillKey": "ItemCreation",
    "levelRequired": 102,
    "baseActionsPerHour": 144,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 986,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 979,
        "quantity": 1
      },
      {
        "itemId": 839,
        "quantity": 1
      }
    ]
  },
  {
    "id": "ItemCreation_10",
    "taskId": 10,
    "name": "demonhide_boots",
    "skillKey": "ItemCreation",
    "levelRequired": 104,
    "baseActionsPerHour": 144,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 987,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 980,
        "quantity": 1
      },
      {
        "itemId": 838,
        "quantity": 1
      }
    ]
  },
  {
    "id": "ItemCreation_11",
    "taskId": 11,
    "name": "silheniks_lunar_belt",
    "skillKey": "ItemCreation",
    "levelRequired": 107,
    "baseActionsPerHour": 144,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 988,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 982,
        "quantity": 1
      },
      {
        "itemId": 883,
        "quantity": 1
      }
    ]
  },
  {
    "id": "ItemCreation_12",
    "taskId": 12,
    "name": "primordial_hide_hat",
    "skillKey": "ItemCreation",
    "levelRequired": 109,
    "baseActionsPerHour": 144,
    "xpPerAction": 0,
    "outputItems": [
      {
        "itemId": 989,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 983,
        "quantity": 1
      },
      {
        "itemId": 840,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Mining_0",
    "taskId": 0,
    "name": "copper_ore",
    "skillKey": "Mining",
    "levelRequired": 1,
    "baseActionsPerHour": 1200,
    "xpPerAction": 7.5,
    "outputItems": [
      {
        "itemId": 29,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Mining_1",
    "taskId": 1,
    "name": "tin_ore",
    "skillKey": "Mining",
    "levelRequired": 1,
    "baseActionsPerHour": 1200,
    "xpPerAction": 7.5,
    "outputItems": [
      {
        "itemId": 28,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Mining_2",
    "taskId": 2,
    "name": "iron_ore",
    "skillKey": "Mining",
    "levelRequired": 15,
    "baseActionsPerHour": 800,
    "xpPerAction": 12,
    "outputItems": [
      {
        "itemId": 30,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Mining_3",
    "taskId": 3,
    "name": "silver_ore",
    "skillKey": "Mining",
    "levelRequired": 25,
    "baseActionsPerHour": 600,
    "xpPerAction": 18.5,
    "outputItems": [
      {
        "itemId": 32,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Mining_4",
    "taskId": 4,
    "name": "coal_ore",
    "skillKey": "Mining",
    "levelRequired": 30,
    "baseActionsPerHour": 480,
    "xpPerAction": 24,
    "outputItems": [
      {
        "itemId": 31,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Mining_5",
    "taskId": 5,
    "name": "gold_ore",
    "skillKey": "Mining",
    "levelRequired": 45,
    "baseActionsPerHour": 171,
    "xpPerAction": 75,
    "outputItems": [
      {
        "itemId": 33,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Mining_6",
    "taskId": 6,
    "name": "platinum_ore",
    "skillKey": "Mining",
    "levelRequired": 55,
    "baseActionsPerHour": 200,
    "xpPerAction": 78,
    "outputItems": [
      {
        "itemId": 39,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Mining_7",
    "taskId": 7,
    "name": "meteorite_ore",
    "skillKey": "Mining",
    "levelRequired": 70,
    "baseActionsPerHour": 138,
    "xpPerAction": 125,
    "outputItems": [
      {
        "itemId": 41,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Mining_8",
    "taskId": 8,
    "name": "diamond_ore",
    "skillKey": "Mining",
    "levelRequired": 75,
    "baseActionsPerHour": 122,
    "xpPerAction": 148,
    "outputItems": [
      {
        "itemId": 378,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Mining_9",
    "taskId": 9,
    "name": "titanium_ore",
    "skillKey": "Mining",
    "levelRequired": 85,
    "baseActionsPerHour": 103,
    "xpPerAction": 180,
    "outputItems": [
      {
        "itemId": 42,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Mining_10",
    "taskId": 10,
    "name": "obsidian_ore",
    "skillKey": "Mining",
    "levelRequired": 95,
    "baseActionsPerHour": 79,
    "xpPerAction": 252,
    "outputItems": [
      {
        "itemId": 958,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Plundering_0",
    "taskId": 0,
    "name": "small_village",
    "skillKey": "Plundering",
    "levelRequired": 1,
    "baseActionsPerHour": 111,
    "xpPerAction": 120,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Plundering_1",
    "taskId": 1,
    "name": "fishing_town",
    "skillKey": "Plundering",
    "levelRequired": 20,
    "baseActionsPerHour": 103,
    "xpPerAction": 150,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Plundering_2",
    "taskId": 2,
    "name": "mining_community",
    "skillKey": "Plundering",
    "levelRequired": 30,
    "baseActionsPerHour": 96,
    "xpPerAction": 180,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Plundering_3",
    "taskId": 3,
    "name": "farm",
    "skillKey": "Plundering",
    "levelRequired": 40,
    "baseActionsPerHour": 90,
    "xpPerAction": 225,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Plundering_4",
    "taskId": 4,
    "name": "small_city",
    "skillKey": "Plundering",
    "levelRequired": 50,
    "baseActionsPerHour": 80,
    "xpPerAction": 290,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Plundering_5",
    "taskId": 5,
    "name": "sports_center",
    "skillKey": "Plundering",
    "levelRequired": 60,
    "baseActionsPerHour": 76,
    "xpPerAction": 360,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Plundering_6",
    "taskId": 6,
    "name": "woodworking_factory",
    "skillKey": "Plundering",
    "levelRequired": 70,
    "baseActionsPerHour": 72,
    "xpPerAction": 400,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Plundering_7",
    "taskId": 7,
    "name": "food_factory",
    "skillKey": "Plundering",
    "levelRequired": 80,
    "baseActionsPerHour": 65,
    "xpPerAction": 500,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Plundering_8",
    "taskId": 8,
    "name": "royal_clan",
    "skillKey": "Plundering",
    "levelRequired": 95,
    "baseActionsPerHour": 60,
    "xpPerAction": 750,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Plundering_9",
    "taskId": 9,
    "name": "ancient_tribe",
    "skillKey": "Plundering",
    "levelRequired": 105,
    "baseActionsPerHour": 45,
    "xpPerAction": 1150,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Plundering_10",
    "taskId": 10,
    "name": "archaeological_society",
    "skillKey": "Plundering",
    "levelRequired": 110,
    "baseActionsPerHour": 15,
    "xpPerAction": 4000,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Smithing_0",
    "taskId": 0,
    "name": "bronze_bar",
    "skillKey": "Smithing",
    "levelRequired": 1,
    "baseActionsPerHour": 1200,
    "xpPerAction": 7.5,
    "outputItems": [
      {
        "itemId": 34,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 28,
        "quantity": 1
      },
      {
        "itemId": 29,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Smithing_1",
    "taskId": 1,
    "name": "iron_bar",
    "skillKey": "Smithing",
    "levelRequired": 15,
    "baseActionsPerHour": 720,
    "xpPerAction": 14,
    "outputItems": [
      {
        "itemId": 35,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 30,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Smithing_2",
    "taskId": 2,
    "name": "silver_bar",
    "skillKey": "Smithing",
    "levelRequired": 25,
    "baseActionsPerHour": 600,
    "xpPerAction": 17.5,
    "outputItems": [
      {
        "itemId": 37,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 32,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Smithing_3",
    "taskId": 3,
    "name": "steel_bar",
    "skillKey": "Smithing",
    "levelRequired": 30,
    "baseActionsPerHour": 554,
    "xpPerAction": 20,
    "outputItems": [
      {
        "itemId": 36,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 30,
        "quantity": 2
      },
      {
        "itemId": 31,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Smithing_4",
    "taskId": 4,
    "name": "gold_bar",
    "skillKey": "Smithing",
    "levelRequired": 50,
    "baseActionsPerHour": 450,
    "xpPerAction": 29,
    "outputItems": [
      {
        "itemId": 38,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 33,
        "quantity": 1
      }
    ]
  },
  {
    "id": "Smithing_5",
    "taskId": 5,
    "name": "platinum_bar",
    "skillKey": "Smithing",
    "levelRequired": 55,
    "baseActionsPerHour": 300,
    "xpPerAction": 50,
    "outputItems": [
      {
        "itemId": 43,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 39,
        "quantity": 3
      },
      {
        "itemId": 31,
        "quantity": 3
      }
    ]
  },
  {
    "id": "Smithing_6",
    "taskId": 6,
    "name": "meteorite_bar",
    "skillKey": "Smithing",
    "levelRequired": 65,
    "baseActionsPerHour": 180,
    "xpPerAction": 100,
    "outputItems": [
      {
        "itemId": 45,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 41,
        "quantity": 3
      },
      {
        "itemId": 31,
        "quantity": 6
      }
    ]
  },
  {
    "id": "Smithing_7",
    "taskId": 7,
    "name": "diamond_bar",
    "skillKey": "Smithing",
    "levelRequired": 70,
    "baseActionsPerHour": 164,
    "xpPerAction": 115,
    "outputItems": [
      {
        "itemId": 379,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 378,
        "quantity": 3
      }
    ]
  },
  {
    "id": "Smithing_8",
    "taskId": 8,
    "name": "titanium_bar",
    "skillKey": "Smithing",
    "levelRequired": 80,
    "baseActionsPerHour": 120,
    "xpPerAction": 225,
    "outputItems": [
      {
        "itemId": 46,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 42,
        "quantity": 3
      },
      {
        "itemId": 31,
        "quantity": 9
      }
    ]
  },
  {
    "id": "Smithing_9",
    "taskId": 9,
    "name": "astronomical_bar",
    "skillKey": "Smithing",
    "levelRequired": 90,
    "baseActionsPerHour": 60,
    "xpPerAction": 2500,
    "outputItems": [
      {
        "itemId": 48,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 47,
        "quantity": 1
      },
      {
        "itemId": 31,
        "quantity": 5000
      }
    ]
  },
  {
    "id": "Smithing_10",
    "taskId": 10,
    "name": "bronze_platebody",
    "skillKey": "Smithing",
    "levelRequired": 1,
    "baseActionsPerHour": 400,
    "xpPerAction": 60,
    "outputItems": [
      {
        "itemId": 49,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 34,
        "quantity": 6
      }
    ]
  },
  {
    "id": "Smithing_11",
    "taskId": 11,
    "name": "bronze_platelegs",
    "skillKey": "Smithing",
    "levelRequired": 1,
    "baseActionsPerHour": 400,
    "xpPerAction": 40,
    "outputItems": [
      {
        "itemId": 50,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 34,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_12",
    "taskId": 12,
    "name": "bronze_helmet",
    "skillKey": "Smithing",
    "levelRequired": 1,
    "baseActionsPerHour": 400,
    "xpPerAction": 20,
    "outputItems": [
      {
        "itemId": 51,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 34,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_13",
    "taskId": 13,
    "name": "bronze_shield",
    "skillKey": "Smithing",
    "levelRequired": 1,
    "baseActionsPerHour": 400,
    "xpPerAction": 40,
    "outputItems": [
      {
        "itemId": 52,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 34,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_14",
    "taskId": 14,
    "name": "iron_platebody",
    "skillKey": "Smithing",
    "levelRequired": 20,
    "baseActionsPerHour": 400,
    "xpPerAction": 75,
    "outputItems": [
      {
        "itemId": 55,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 35,
        "quantity": 6
      }
    ]
  },
  {
    "id": "Smithing_15",
    "taskId": 15,
    "name": "iron_platelegs",
    "skillKey": "Smithing",
    "levelRequired": 20,
    "baseActionsPerHour": 400,
    "xpPerAction": 50,
    "outputItems": [
      {
        "itemId": 56,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 35,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_16",
    "taskId": 16,
    "name": "iron_helmet",
    "skillKey": "Smithing",
    "levelRequired": 20,
    "baseActionsPerHour": 400,
    "xpPerAction": 25,
    "outputItems": [
      {
        "itemId": 57,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 35,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_17",
    "taskId": 17,
    "name": "iron_shield",
    "skillKey": "Smithing",
    "levelRequired": 20,
    "baseActionsPerHour": 400,
    "xpPerAction": 50,
    "outputItems": [
      {
        "itemId": 58,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 35,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_18",
    "taskId": 18,
    "name": "silver_amulet",
    "skillKey": "Smithing",
    "levelRequired": 30,
    "baseActionsPerHour": 1200,
    "xpPerAction": 35,
    "outputItems": [
      {
        "itemId": 68,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 37,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_19",
    "taskId": 19,
    "name": "silver_ring",
    "skillKey": "Smithing",
    "levelRequired": 30,
    "baseActionsPerHour": 1200,
    "xpPerAction": 35,
    "outputItems": [
      {
        "itemId": 67,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 37,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_20",
    "taskId": 20,
    "name": "silver_bracelet",
    "skillKey": "Smithing",
    "levelRequired": 30,
    "baseActionsPerHour": 1200,
    "xpPerAction": 35,
    "outputItems": [
      {
        "itemId": 69,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 37,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_21",
    "taskId": 21,
    "name": "silver_earrings",
    "skillKey": "Smithing",
    "levelRequired": 30,
    "baseActionsPerHour": 1200,
    "xpPerAction": 35,
    "outputItems": [
      {
        "itemId": 70,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 37,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_28",
    "taskId": 28,
    "name": "steel_platebody",
    "skillKey": "Smithing",
    "levelRequired": 35,
    "baseActionsPerHour": 400,
    "xpPerAction": 90,
    "outputItems": [
      {
        "itemId": 61,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 36,
        "quantity": 6
      }
    ]
  },
  {
    "id": "Smithing_29",
    "taskId": 29,
    "name": "steel_platelegs",
    "skillKey": "Smithing",
    "levelRequired": 35,
    "baseActionsPerHour": 400,
    "xpPerAction": 60,
    "outputItems": [
      {
        "itemId": 62,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 36,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_30",
    "taskId": 30,
    "name": "steel_helmet",
    "skillKey": "Smithing",
    "levelRequired": 35,
    "baseActionsPerHour": 400,
    "xpPerAction": 30,
    "outputItems": [
      {
        "itemId": 63,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 36,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_31",
    "taskId": 31,
    "name": "steel_shield",
    "skillKey": "Smithing",
    "levelRequired": 35,
    "baseActionsPerHour": 400,
    "xpPerAction": 60,
    "outputItems": [
      {
        "itemId": 64,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 36,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_32",
    "taskId": 32,
    "name": "gold_amulet",
    "skillKey": "Smithing",
    "levelRequired": 50,
    "baseActionsPerHour": 1200,
    "xpPerAction": 40,
    "outputItems": [
      {
        "itemId": 72,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 38,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_33",
    "taskId": 33,
    "name": "gold_ring",
    "skillKey": "Smithing",
    "levelRequired": 50,
    "baseActionsPerHour": 1200,
    "xpPerAction": 40,
    "outputItems": [
      {
        "itemId": 71,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 38,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_34",
    "taskId": 34,
    "name": "gold_bracelet",
    "skillKey": "Smithing",
    "levelRequired": 50,
    "baseActionsPerHour": 1200,
    "xpPerAction": 40,
    "outputItems": [
      {
        "itemId": 73,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 38,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_35",
    "taskId": 35,
    "name": "gold_earrings",
    "skillKey": "Smithing",
    "levelRequired": 50,
    "baseActionsPerHour": 1200,
    "xpPerAction": 40,
    "outputItems": [
      {
        "itemId": 74,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 38,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_42",
    "taskId": 42,
    "name": "platinum_platebody",
    "skillKey": "Smithing",
    "levelRequired": 55,
    "baseActionsPerHour": 400,
    "xpPerAction": 150,
    "outputItems": [
      {
        "itemId": 75,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 43,
        "quantity": 6
      }
    ]
  },
  {
    "id": "Smithing_43",
    "taskId": 43,
    "name": "platinum_platelegs",
    "skillKey": "Smithing",
    "levelRequired": 55,
    "baseActionsPerHour": 400,
    "xpPerAction": 100,
    "outputItems": [
      {
        "itemId": 76,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 43,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_44",
    "taskId": 44,
    "name": "platinum_helmet",
    "skillKey": "Smithing",
    "levelRequired": 55,
    "baseActionsPerHour": 400,
    "xpPerAction": 50,
    "outputItems": [
      {
        "itemId": 77,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 43,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_45",
    "taskId": 45,
    "name": "platinum_shield",
    "skillKey": "Smithing",
    "levelRequired": 55,
    "baseActionsPerHour": 400,
    "xpPerAction": 100,
    "outputItems": [
      {
        "itemId": 78,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 43,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_46",
    "taskId": 46,
    "name": "meteorite_platebody",
    "skillKey": "Smithing",
    "levelRequired": 70,
    "baseActionsPerHour": 400,
    "xpPerAction": 210,
    "outputItems": [
      {
        "itemId": 81,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 45,
        "quantity": 6
      }
    ]
  },
  {
    "id": "Smithing_47",
    "taskId": 47,
    "name": "meteorite_platelegs",
    "skillKey": "Smithing",
    "levelRequired": 70,
    "baseActionsPerHour": 400,
    "xpPerAction": 140,
    "outputItems": [
      {
        "itemId": 82,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 45,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_48",
    "taskId": 48,
    "name": "meteorite_helmet",
    "skillKey": "Smithing",
    "levelRequired": 70,
    "baseActionsPerHour": 400,
    "xpPerAction": 70,
    "outputItems": [
      {
        "itemId": 84,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 45,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_49",
    "taskId": 49,
    "name": "meteorite_shield",
    "skillKey": "Smithing",
    "levelRequired": 70,
    "baseActionsPerHour": 400,
    "xpPerAction": 140,
    "outputItems": [
      {
        "itemId": 83,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 45,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_50",
    "taskId": 50,
    "name": "diamond_amulet",
    "skillKey": "Smithing",
    "levelRequired": 75,
    "baseActionsPerHour": 800,
    "xpPerAction": 70,
    "outputItems": [
      {
        "itemId": 375,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 379,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_51",
    "taskId": 51,
    "name": "diamond_ring",
    "skillKey": "Smithing",
    "levelRequired": 75,
    "baseActionsPerHour": 800,
    "xpPerAction": 70,
    "outputItems": [
      {
        "itemId": 374,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 379,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_52",
    "taskId": 52,
    "name": "diamond_bracelet",
    "skillKey": "Smithing",
    "levelRequired": 75,
    "baseActionsPerHour": 800,
    "xpPerAction": 70,
    "outputItems": [
      {
        "itemId": 376,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 379,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_53",
    "taskId": 53,
    "name": "diamond_earrings",
    "skillKey": "Smithing",
    "levelRequired": 75,
    "baseActionsPerHour": 800,
    "xpPerAction": 70,
    "outputItems": [
      {
        "itemId": 377,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 379,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_60",
    "taskId": 60,
    "name": "titanium_platebody",
    "skillKey": "Smithing",
    "levelRequired": 85,
    "baseActionsPerHour": 400,
    "xpPerAction": 240,
    "outputItems": [
      {
        "itemId": 87,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 46,
        "quantity": 6
      }
    ]
  },
  {
    "id": "Smithing_61",
    "taskId": 61,
    "name": "titanium_platelegs",
    "skillKey": "Smithing",
    "levelRequired": 85,
    "baseActionsPerHour": 400,
    "xpPerAction": 160,
    "outputItems": [
      {
        "itemId": 88,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 46,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_62",
    "taskId": 62,
    "name": "titanium_helmet",
    "skillKey": "Smithing",
    "levelRequired": 85,
    "baseActionsPerHour": 400,
    "xpPerAction": 80,
    "outputItems": [
      {
        "itemId": 89,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 46,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_63",
    "taskId": 63,
    "name": "titanium_shield",
    "skillKey": "Smithing",
    "levelRequired": 85,
    "baseActionsPerHour": 400,
    "xpPerAction": 160,
    "outputItems": [
      {
        "itemId": 90,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 46,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_64",
    "taskId": 64,
    "name": "astronomical_platebody",
    "skillKey": "Smithing",
    "levelRequired": 95,
    "baseActionsPerHour": 400,
    "xpPerAction": 3000,
    "outputItems": [
      {
        "itemId": 93,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 48,
        "quantity": 6
      }
    ]
  },
  {
    "id": "Smithing_65",
    "taskId": 65,
    "name": "astronomical_platelegs",
    "skillKey": "Smithing",
    "levelRequired": 95,
    "baseActionsPerHour": 400,
    "xpPerAction": 2000,
    "outputItems": [
      {
        "itemId": 94,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 48,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_66",
    "taskId": 66,
    "name": "astronomical_helmet",
    "skillKey": "Smithing",
    "levelRequired": 95,
    "baseActionsPerHour": 400,
    "xpPerAction": 1000,
    "outputItems": [
      {
        "itemId": 95,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 48,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_67",
    "taskId": 67,
    "name": "astronomical_shield",
    "skillKey": "Smithing",
    "levelRequired": 95,
    "baseActionsPerHour": 400,
    "xpPerAction": 2000,
    "outputItems": [
      {
        "itemId": 96,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 48,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_68",
    "taskId": 68,
    "name": "otherworldly_platebody",
    "skillKey": "Smithing",
    "levelRequired": 110,
    "baseActionsPerHour": 400,
    "xpPerAction": 6000,
    "outputItems": [
      {
        "itemId": 923,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 93,
        "quantity": 1
      },
      {
        "itemId": 927,
        "quantity": 6
      }
    ]
  },
  {
    "id": "Smithing_69",
    "taskId": 69,
    "name": "otherworldly_platelegs",
    "skillKey": "Smithing",
    "levelRequired": 108,
    "baseActionsPerHour": 400,
    "xpPerAction": 4000,
    "outputItems": [
      {
        "itemId": 924,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 94,
        "quantity": 1
      },
      {
        "itemId": 927,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_70",
    "taskId": 70,
    "name": "otherworldly_helmet",
    "skillKey": "Smithing",
    "levelRequired": 104,
    "baseActionsPerHour": 400,
    "xpPerAction": 2000,
    "outputItems": [
      {
        "itemId": 925,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 95,
        "quantity": 1
      },
      {
        "itemId": 927,
        "quantity": 2
      }
    ]
  },
  {
    "id": "Smithing_71",
    "taskId": 71,
    "name": "otherworldly_shield",
    "skillKey": "Smithing",
    "levelRequired": 106,
    "baseActionsPerHour": 400,
    "xpPerAction": 4000,
    "outputItems": [
      {
        "itemId": 922,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 96,
        "quantity": 1
      },
      {
        "itemId": 927,
        "quantity": 4
      }
    ]
  },
  {
    "id": "Smithing_72",
    "taskId": 72,
    "name": "otherworldly_bar",
    "skillKey": "Smithing",
    "levelRequired": 102,
    "baseActionsPerHour": 60,
    "xpPerAction": 5000,
    "outputItems": [
      {
        "itemId": 927,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 926,
        "quantity": 1
      },
      {
        "itemId": 47,
        "quantity": 2
      },
      {
        "itemId": 41,
        "quantity": 10000
      },
      {
        "itemId": 42,
        "quantity": 5000
      }
    ]
  },
  {
    "id": "Smithing_73",
    "taskId": 73,
    "name": "tempered_obsidian",
    "skillKey": "Smithing",
    "levelRequired": 95,
    "baseActionsPerHour": 92,
    "xpPerAction": 315,
    "outputItems": [
      {
        "itemId": 959,
        "quantity": 1
      }
    ],
    "inputItems": [
      {
        "itemId": 958,
        "quantity": 3
      },
      {
        "itemId": 31,
        "quantity": 12
      }
    ]
  },
  {
    "id": "Woodcutting_0",
    "taskId": 0,
    "name": "spruce",
    "skillKey": "Woodcutting",
    "levelRequired": 1,
    "baseActionsPerHour": 1200,
    "xpPerAction": 7.5,
    "outputItems": [],
    "inputItems": []
  },
  {
    "id": "Woodcutting_1",
    "taskId": 1,
    "name": "pine",
    "skillKey": "Woodcutting",
    "levelRequired": 10,
    "baseActionsPerHour": 720,
    "xpPerAction": 14,
    "outputItems": [
      {
        "itemId": 1,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Woodcutting_2",
    "taskId": 2,
    "name": "oak",
    "skillKey": "Woodcutting",
    "levelRequired": 20,
    "baseActionsPerHour": 600,
    "xpPerAction": 17.5,
    "outputItems": [
      {
        "itemId": 6,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Woodcutting_3",
    "taskId": 3,
    "name": "maple",
    "skillKey": "Woodcutting",
    "levelRequired": 30,
    "baseActionsPerHour": 554,
    "xpPerAction": 20,
    "outputItems": [
      {
        "itemId": 7,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Woodcutting_4",
    "taskId": 4,
    "name": "teak",
    "skillKey": "Woodcutting",
    "levelRequired": 40,
    "baseActionsPerHour": 450,
    "xpPerAction": 25,
    "outputItems": [
      {
        "itemId": 8,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Woodcutting_5",
    "taskId": 5,
    "name": "chestnut",
    "skillKey": "Woodcutting",
    "levelRequired": 50,
    "baseActionsPerHour": 360,
    "xpPerAction": 35,
    "outputItems": [
      {
        "itemId": 2,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Woodcutting_6",
    "taskId": 6,
    "name": "mahogany",
    "skillKey": "Woodcutting",
    "levelRequired": 60,
    "baseActionsPerHour": 288,
    "xpPerAction": 50,
    "outputItems": [
      {
        "itemId": 9,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Woodcutting_7",
    "taskId": 7,
    "name": "yew",
    "skillKey": "Woodcutting",
    "levelRequired": 70,
    "baseActionsPerHour": 240,
    "xpPerAction": 67.5,
    "outputItems": [
      {
        "itemId": 10,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Woodcutting_8",
    "taskId": 8,
    "name": "redwood",
    "skillKey": "Woodcutting",
    "levelRequired": 80,
    "baseActionsPerHour": 206,
    "xpPerAction": 90,
    "outputItems": [
      {
        "itemId": 406,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Woodcutting_9",
    "taskId": 9,
    "name": "magical",
    "skillKey": "Woodcutting",
    "levelRequired": 90,
    "baseActionsPerHour": 180,
    "xpPerAction": 110,
    "outputItems": [
      {
        "itemId": 407,
        "quantity": 1
      }
    ],
    "inputItems": []
  },
  {
    "id": "Woodcutting_10",
    "taskId": 10,
    "name": "ignis",
    "skillKey": "Woodcutting",
    "levelRequired": 105,
    "baseActionsPerHour": 24,
    "xpPerAction": 935,
    "outputItems": [
      {
        "itemId": 912,
        "quantity": 1
      }
    ],
    "inputItems": []
  }
]

export const ACTIVITIES_BY_ID: Map<string, ActivityDefinition> = new Map(ACTIVITIES.map((a) => [a.id, a]))
